# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e910120a87997648cd03f8b6e073e5da"
name = "viome-internal-extensions-dev"
handle = "viome-internal-extensions-dev"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "staging-viome.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
