# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-07"

[[extensions]]
name = "delayed-shipping-banner"
handle = "delayed-shipping-banner"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.delivery-address.render-before"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = false

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "delayedProductsSku"
type = "multi_line_text_field"
name = "Delayed Product SKUs"
description = "Enter the SKUs for the delayed products"

[[extensions.settings.fields]]
key = "domesticCountryCodes"
type = "multi_line_text_field"
name = "Domestic Country Codes"
description = "Enter the Domestic zones Country Codes on the ISO 3166 Alpha-2 format"

[[extensions.settings.fields]]
key = "delayedShippingModality"
type = "single_line_text_field"
name = "Delayed Shipping Modality"
description = "Enter the delay modality to which this alert should be displayed"

[[extensions.settings.fields.validations]]
name = "choices"
value = '["all", "domestic", "international"]'

[[extensions.settings.fields]]
key = "minDelayDays"
type = "number_integer"
name = "Minimum day count of delays"
description = "Enter the minimum amount of days that the delivery can be delayed"

[[extensions.settings.fields]]
key = "maxDelayDays"
type = "number_integer"
name = "Maximum day count of delays"
description = "Enter the maximum amount of days that the delivery can be delayed"

